"""
Nexus 2.0 — Layer 5: Human Control (Feedback & RLHF)
=====================================================
API endpoints for analyst feedback on generated SARs.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from app.core.database import save_feedback, get_feedback_stats
from app.core.logger import logger

router = APIRouter(tags=["Feedback"])


class FeedbackRequest(BaseModel):
    """Request to submit analyst feedback on a generated SAR."""
    
    case_id: str = Field(..., description="Unique identifier for the case")
    original_sar: dict[str, Any] = Field(..., description="Original SAR draft generated by the system")
    edited_sar: dict[str, Any] | None = Field(None, description="Analyst-edited SAR (if modifications made)")
    outcome: str | None = Field(
        None, 
        pattern="^(true_positive|false_positive|pending)$",
        description="Analyst determination: true_positive, false_positive, or pending"
    )
    analyst_notes: str | None = Field(None, description="Free-form notes from the analyst")


class FeedbackResponse(BaseModel):
    """Response confirming feedback submission."""
    
    success: bool = True
    feedback_id: int
    case_id: str
    message: str


class FeedbackStatsResponse(BaseModel):
    """Feedback statistics for analytics."""
    
    total: int
    true_positives: int
    false_positives: int
    pending: int
    analyst_id: str | None = None


@router.post(
    "/feedback",
    response_model=FeedbackResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Submit SAR Feedback (RLHF)",
    description=(
        "Layer 5: Human Control — Analysts submit feedback on generated SARs "
        "including edits and true/false positive outcomes for RLHF training."
    ),
)
async def submit_feedback(
    body: FeedbackRequest,
) -> FeedbackResponse:
    """Submit analyst feedback for a generated SAR.
    
    This endpoint captures:
    - Original SAR draft
    - Analyst edits/corrections
    - Outcome determination (true_positive, false_positive, pending)
    - Analyst notes
    
    Data is persisted to PostgreSQL for RLHF and audit purposes.
    """
    try:
        feedback_id = await save_feedback(
            case_id=body.case_id,
            analyst_id="public-analyst",
            original_sar=body.original_sar,
            edited_sar=body.edited_sar,
            outcome=body.outcome,
            analyst_notes=body.analyst_notes,
        )
        
        logger.info(
            "Feedback submitted for case %s by analyst %s (outcome=%s)",
            body.case_id,
            "public-analyst",
            body.outcome,
        )
        
        return FeedbackResponse(
            success=True,
            feedback_id=feedback_id,
            case_id=body.case_id,
            message="Feedback recorded successfully",
        )
        
    except Exception as exc:
        logger.error("Failed to save feedback: %s", str(exc))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "success": False,
                "error": "Failed to save feedback",
                "detail": str(exc),
            },
        )


@router.get(
    "/feedback/stats",
    response_model=FeedbackStatsResponse,
    status_code=status.HTTP_200_OK,
    summary="Get Feedback Statistics",
    description="Retrieve feedback statistics for all analysts or a specific analyst.",
)
async def feedback_stats(
    analyst_id: str | None = None,
) -> FeedbackStatsResponse:
    """Get feedback statistics.
    
    Args:
        analyst_id: Optional filter for specific analyst
        
    Returns:
        Counts of total, true_positive, false_positive, and pending feedback.
    """
    try:
        stats = await get_feedback_stats(analyst_id)
        return FeedbackStatsResponse(
            total=stats["total"],
            true_positives=stats["true_positives"],
            false_positives=stats["false_positives"],
            pending=stats["pending"],
            analyst_id=analyst_id,
        )
    except Exception as exc:
        logger.error("Failed to fetch feedback stats: %s", str(exc))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "success": False,
                "error": "Failed to fetch feedback statistics",
            },
        )
